config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tops#show'

  namespace :users do
    resources :posts
    resources :all_posts, only: %i[index show]
  end

  resource :top, only: %i[show]
  resource :about, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true

  scope :default_order, -> { order(id: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    users_posts_path
  end

  def after_sign_up_path_for(resource)
    users_posts_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def show
  end
end

app/controllers/users/all_posts_controller.rb
class Users::AllPostsController < Users::ApplicationController
  before_action :set_post, only: %i[show]

  def index
    @posts = Post.default_order
  end

  def show
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users/posts_controller.rb
class Users::PostsController < Users::ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = current_user.posts.default_order
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to users_posts_path, notice: t('controllers.created')
    else
      flash.now[:alert] = t('controllers.failed_create')
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to users_posts_path, notice: t('controllers.updated')
    else
      flash.now[:alert] = t('controllers.failed_update')
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to users_posts_path, notice: t('controllers.destroyed')
  end

  private

  def post_params
    params.require(:post).permit %i[title content url]
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abouts/show.html.haml
.mt-5.text-center
  %p 忙しい毎日、私たちのスケジュール帳は週末も予定でびっちり埋まっている。
  %p 休みの日も急に予定が空いたりすると、「何かをしなくちゃ」と思ってしまう人も多いのではないだろうか？
  %br
  %p 普段の日もちょっとしたすき間時間には、ついスマホをいじってしまう。
  %p そうしてしまったが最後、今日やるべき「To Do List（やることリスト）」はどんどん長くなり、
  %p クルクルと回し車を走るハムスターのように、私たちは走り続けてしまう。。
  %br
  %p そんな生活をスローダウンさせて、「何もしない」時間を味わうこと
  %strong それが「Niksen（ニクセン）」
  %blockquote{ cite: 'https://ampmedia.jp/2020/02/14/niksen/' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ニクセン
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
  %body
    .navbar.navbar-light.shadow
      .container-fluid
        .navbar-brand.h1
          = link_to root_path do 
            = image_tag 'logo.png', alt: 'ニクセン', class: 'header__logo-image'
        .nav
          .nav-item.me-3
            = link_to 'ニクセンとは', about_path, class: 'header__link_content'
          .nav-item.me-3
            = link_to 'ユーザーログイン', new_user_session_path, class: 'header__link_content'
    = yield

app/views/layouts/users/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Niksen
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
  %body
    .navbar.navbar-light.shadow
      .container-fluid
        .navbar-brand.h1
          = link_to users_posts_path do 
            = image_tag 'logo.png', alt: 'ニクセン', class: 'header__logo-image'
        .nav
          .nav-item.me-3
            = link_to 'わたしのニクセン体験記', users_posts_path, class: 'header__link_content'
          .nav-item.me-3
            = link_to 'みんなのニクセン体験記', users_all_posts_path, class: 'header__link_content'
          .nav-item.me-3
            = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header__link_content'
    .container.mt-4
      - if notice.present? 
        .alert-success.text-center
          .far.fa-check-circle
          = notice
      - if alert.present?
        .alert-danger.text-center
          .far.fa-times-circle
          = alert
      = yield

app/views/tops/show.html.haml
= image_tag '1.jpeg', id:'mypic', class: 'top__slideshow-image'

:javascript
  var pics_src = new Array("assets/1.jpeg","assets/2.jpeg","assets/3.jpeg","assets/4.jpeg","assets/5.jpeg","assets/6.jpeg");
  var num = -1;

  slideshow_timer();

  function slideshow_timer(){
    if (num == 5){
        num = 0;
    } 
    else {
        num ++;
    }
    document.getElementById("mypic").src=pics_src[num];
    setTimeout("slideshow_timer()",2000); 
  }

app/views/users/all_posts/index.html.haml
%h2 ニクセン体験記
- @posts.each do |post|
  .list-group
    %a.list-group-item.list-group-item-action{href: users_all_post_path(post)}
      = post.title

app/views/users/all_posts/show.html.haml
.card 
  .card-header
    = @post.title
  .card-body
    = simple_format(@post.content)

app/views/users/posts/_form.html.haml
= simple_form_for [:users, @post] do |f|
  = f.input :title
  = f.input :content
  = f.input :url
  = f.button :submit, class: 'btn btn-primary mt-3'

app/views/users/posts/edit.html.haml
%h1 Users::Posts#edit
%p Find me in app/views/users/posts/edit.html.haml
= render 'form'

app/views/users/posts/index.html.haml
%h2 ニクセン体験記
- @posts.each do |post|
  .list-group
    %a.list-group-item.list-group-item-action{href: users_post_path(post)}
      = post.title
= link_to 'ニクソン体験を投稿する', new_users_post_path, class: 'mt-3 btn btn-primary'

app/views/users/posts/new.html.haml
%h1 Users::Posts#new
%p Find me in app/views/users/posts/new.html.haml
= render 'form'

app/views/users/posts/show.html.haml
.card 
  .card-header
    = @post.title
  .card-body
    = simple_format(@post.content)

= link_to edit_users_post_path do
  %i.fas.fa-external-link-alt.btn.btn-primary.mt-3.me-3
= link_to users_post_path, method: :delete, data:{ confirm: '削除してもよろしいですか？'} do
  %i.far.fa-trash-alt.btn.btn-danger.mt-3